### ISSUE TITLE
你好打扰下

### ISSUE THREAD

**Issue by xp12047** [westinyang/WebView2RuntimeArchive#1]
看到你这个项目我很开心。当时我正寻找不含edge的WebView。  
我下载了你发布的最新版也解压了。然后我就把本机的webvieew给卸载了。我想应该不需要它了。但我不知道该怎么设置你发布的那个WebView2让它起作用。我有几个应用都需要webview2现在他们不管用了打不开了。。。官方的文档我看不懂该怎么设置。拜托有空帮忙看看。

**Comment by westinyang** [comment]
@xp12047 其实你完全不需要卸载本机的Edge或WebView2组件，只需要在编码阶段加载指定的固定版本运行时即可，给你贴一段我的代码片段：

```C#
private async void Form1_Load(object sender, EventArgs e)
{
    await InitializeAsync(webView2);
}

/// <summary>
/// 初始化WebView2运行环境
/// </summary>
/// <returns></returns>
public async Task InitializeAsync(WebView2 webView2)
{
    // 查找固定版本运行环境
    // 把固定版本运行环境解压到可执行程序的同级目录，例如：项目\bin\Debug 或者 项目\bin\Release
    string fixedRumtimeVersionPath = "Microsoft.WebView2.FixedVersionRuntime.89.0.774.54.x86";
    string fixedRumtimeVersion = CoreWebView2Environment.GetAvailableBrowserVersionString(fixedRumtimeVersionPath);
    Console.WriteLine("使用固定版本运行环境：" + fixedRumtimeVersion);
    // 创建 CoreWebView2 运行环境
    CoreWebView2Environment webView2Environment = await CoreWebView2Environment.CreateAsync(fixedRumtimeVersionPath);
    // 等待 CoreWebView2 初始化
    await webView2.EnsureCoreWebView2Async(webView2Environment);
}
```

如果需要技术交流
- 欢迎加入我的知识星球：https://docs.qq.com/doc/DQVlkcnlQUEFiQ3Rl
- 或者CefSharp/WebView2等嵌入式浏览器的技术交流群：1021597231

**Comment by xp12047** [comment]
> @xp12047其实你完全不需要加载本机的Edge或者WebView2组件，只需要在编码阶段加载指定的固定版本运行时即可，给你贴：一段我的代码
> 
> ```cs
> private async void Form1_Load(object sender, EventArgs e)
> {
>     await InitializeAsync(webView2);
> }
> 
> /// <summary>
> /// 初始化WebView2运行环境
> /// </summary>
> /// <returns></returns>
> public async Task InitializeAsync(WebView2 webView2)
> {
>     // 查找固定版本运行环境
>     // 把固定版本运行环境解压到可执行程序的同级目录，例如：项目\bin\Debug 或者 项目\bin\Release
>     string fixedRumtimeVersionPath = "Microsoft.WebView2.FixedVersionRuntime.89.0.774.54.x86";
>     string fixedRumtimeVersion = CoreWebView2Environment.GetAvailableBrowserVersionString(fixedRumtimeVersionPath);
>     Console.WriteLine("使用固定版本运行环境：" + fixedRumtimeVersion);
>     // 创建 CoreWebView2 运行环境
>     CoreWebView2Environment webView2Environment = await CoreWebView2Environment.CreateAsync(fixedRumtimeVersionPath);
>     // 等待 CoreWebView2 初始化
>     await webView2.EnsureCoreWebView2Async(webView2Environment);
> }
> ```
> 
> 如果需要技术交流
> 
> * 欢迎加入我的知识星球：https://docs.qq.com/doc/DQVlkcnlQUEFiQ3Rl
> * 或者CefSharp/WebView2等插件式浏览器的技术交流群：1021597231

好，谢谢
